appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: WlaIgFHUr1YK8MoZJP6AdWBgsLIOEyI11RLKQDXteQAylYlfDq3Q8Dgn1vzG7MTKu/4Z5aF3C2FcmX98p1TYx2UDmF1ZT1HuuMzckG4oAP05BsgZBpz20asyLzOPVA8QS6rfFkuC4JbTho8yEQ+bKoTVidsKTAsb9PNZ8+wFr8snZfnepjKu0RnaLtU0WFEn8luGTLLrI+RKA3mft3MYa+ML1yX44B4e0AcwYVxYV8kY7T79LRDwMLDzfICwrvTKuP/VK2RrWhX/9slLdI2xBrqjq7nT2e51gs9XUj6cSZJSCYy90JlfKzGgMZhh/Ew9X/7ABu7eyp9utIalD7PxHmnrbk63K3NappC9kNhF3ld0ZTjV+z4rcUfTp/sC3Px92rLeQoYA1ZknZAvXumy3cE38hR5OYphUl9zi8WFjlsamJBADksSkxPy+Us0cLHno6/9MmPRI69D36m6ph934iHWr7j/UvhQE8d1PPqnDfc9MhaGsUAz3sBbQJHMzLFh6VhpLMPO8HpLkmNxDRPk0sVXH4GF7TFbUXPBJg+0Cyn6+UrszNkNuSWQAIJaPXylDjxXF6jZDtJTvowknvrsIPJp+Ps1XhMMwZs6xSz7dL978VrBsjTMWgVU9/Outm0ydxVqxfexsA076NoRFqF+VCdC4DKppVC43I86xd27gy8w=}
bot:
  automerge: true
